<?xml version="1.0" encoding="utf-8"?><Database Name="Kcs" Class="KcsDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HP-PC\SQL2014;Initial Catalog=Kcs;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KcsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admin">
    <Type Name="Admin">
      <Column Name="admin_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="admin_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Player">
    <Type Name="Player">
      <Column Name="player_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="player_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sex" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Test" Member="Test">
    <Type Name="Test">
      <Column Name="TestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestTitle" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TestAns1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TestAns2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TestAns3" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TestAns4" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RightAns" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Result" Member="Result">
    <Type Name="Result">
      <Column Name="Result_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Players" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>