#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Kcs")]
public partial class KcsDataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertAdmin(Admin instance);
  partial void UpdateAdmin(Admin instance);
  partial void DeleteAdmin(Admin instance);
  partial void InsertPlayer(Player instance);
  partial void UpdatePlayer(Player instance);
  partial void DeletePlayer(Player instance);
  partial void InsertTest(Test instance);
  partial void UpdateTest(Test instance);
  partial void DeleteTest(Test instance);
  partial void InsertResult(Result instance);
  partial void UpdateResult(Result instance);
  partial void DeleteResult(Result instance);
  #endregion
	
	public KcsDataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["KcsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public KcsDataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public KcsDataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public KcsDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public KcsDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Admin> Admin
	{
		get
		{
			return this.GetTable<Admin>();
		}
	}
	
	public System.Data.Linq.Table<Player> Player
	{
		get
		{
			return this.GetTable<Player>();
		}
	}
	
	public System.Data.Linq.Table<Test> Test
	{
		get
		{
			return this.GetTable<Test>();
		}
	}
	
	public System.Data.Linq.Table<Result> Result
	{
		get
		{
			return this.GetTable<Result>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _admin_id;
	
	private string _admin_name;
	
	private string _password;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_idChanging(int value);
    partial void Onadmin_idChanged();
    partial void Onadmin_nameChanging(string value);
    partial void Onadmin_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public Admin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int admin_id
	{
		get
		{
			return this._admin_id;
		}
		set
		{
			if ((this._admin_id != value))
			{
				this.Onadmin_idChanging(value);
				this.SendPropertyChanging();
				this._admin_id = value;
				this.SendPropertyChanged("admin_id");
				this.Onadmin_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string admin_name
	{
		get
		{
			return this._admin_name;
		}
		set
		{
			if ((this._admin_name != value))
			{
				this.Onadmin_nameChanging(value);
				this.SendPropertyChanging();
				this._admin_name = value;
				this.SendPropertyChanged("admin_name");
				this.Onadmin_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Player")]
public partial class Player : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _player_id;
	
	private string _player_name;
	
	private string _password;
	
	private string _sex;
	
	private int _age;
	
	private string _email;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplayer_idChanging(int value);
    partial void Onplayer_idChanged();
    partial void Onplayer_nameChanging(string value);
    partial void Onplayer_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnageChanging(int value);
    partial void OnageChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public Player()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_player_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int player_id
	{
		get
		{
			return this._player_id;
		}
		set
		{
			if ((this._player_id != value))
			{
				this.Onplayer_idChanging(value);
				this.SendPropertyChanging();
				this._player_id = value;
				this.SendPropertyChanged("player_id");
				this.Onplayer_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_player_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string player_name
	{
		get
		{
			return this._player_name;
		}
		set
		{
			if ((this._player_name != value))
			{
				this.Onplayer_nameChanging(value);
				this.SendPropertyChanging();
				this._player_name = value;
				this.SendPropertyChanged("player_name");
				this.Onplayer_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="Char(10) NOT NULL", CanBeNull=false)]
	public string sex
	{
		get
		{
			return this._sex;
		}
		set
		{
			if ((this._sex != value))
			{
				this.OnsexChanging(value);
				this.SendPropertyChanging();
				this._sex = value;
				this.SendPropertyChanged("sex");
				this.OnsexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int NOT NULL")]
	public int age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Test")]
public partial class Test : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _TestID;
	
	private string _TestTitle;
	
	private string _TestAns1;
	
	private string _TestAns2;
	
	private string _TestAns3;
	
	private string _TestAns4;
	
	private string _RightAns;
	
	private System.DateTime _Time;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestIDChanging(int value);
    partial void OnTestIDChanged();
    partial void OnTestTitleChanging(string value);
    partial void OnTestTitleChanged();
    partial void OnTestAns1Changing(string value);
    partial void OnTestAns1Changed();
    partial void OnTestAns2Changing(string value);
    partial void OnTestAns2Changed();
    partial void OnTestAns3Changing(string value);
    partial void OnTestAns3Changed();
    partial void OnTestAns4Changing(string value);
    partial void OnTestAns4Changed();
    partial void OnRightAnsChanging(string value);
    partial void OnRightAnsChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    #endregion
	
	public Test()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int TestID
	{
		get
		{
			return this._TestID;
		}
		set
		{
			if ((this._TestID != value))
			{
				this.OnTestIDChanging(value);
				this.SendPropertyChanging();
				this._TestID = value;
				this.SendPropertyChanged("TestID");
				this.OnTestIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestTitle", DbType="VarChar(200)")]
	public string TestTitle
	{
		get
		{
			return this._TestTitle;
		}
		set
		{
			if ((this._TestTitle != value))
			{
				this.OnTestTitleChanging(value);
				this.SendPropertyChanging();
				this._TestTitle = value;
				this.SendPropertyChanged("TestTitle");
				this.OnTestTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestAns1", DbType="VarChar(100)")]
	public string TestAns1
	{
		get
		{
			return this._TestAns1;
		}
		set
		{
			if ((this._TestAns1 != value))
			{
				this.OnTestAns1Changing(value);
				this.SendPropertyChanging();
				this._TestAns1 = value;
				this.SendPropertyChanged("TestAns1");
				this.OnTestAns1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestAns2", DbType="VarChar(100)")]
	public string TestAns2
	{
		get
		{
			return this._TestAns2;
		}
		set
		{
			if ((this._TestAns2 != value))
			{
				this.OnTestAns2Changing(value);
				this.SendPropertyChanging();
				this._TestAns2 = value;
				this.SendPropertyChanged("TestAns2");
				this.OnTestAns2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestAns3", DbType="VarChar(100)")]
	public string TestAns3
	{
		get
		{
			return this._TestAns3;
		}
		set
		{
			if ((this._TestAns3 != value))
			{
				this.OnTestAns3Changing(value);
				this.SendPropertyChanging();
				this._TestAns3 = value;
				this.SendPropertyChanged("TestAns3");
				this.OnTestAns3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestAns4", DbType="VarChar(100)")]
	public string TestAns4
	{
		get
		{
			return this._TestAns4;
		}
		set
		{
			if ((this._TestAns4 != value))
			{
				this.OnTestAns4Changing(value);
				this.SendPropertyChanging();
				this._TestAns4 = value;
				this.SendPropertyChanged("TestAns4");
				this.OnTestAns4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightAns", DbType="VarChar(100)")]
	public string RightAns
	{
		get
		{
			return this._RightAns;
		}
		set
		{
			if ((this._RightAns != value))
			{
				this.OnRightAnsChanging(value);
				this.SendPropertyChanging();
				this._RightAns = value;
				this.SendPropertyChanged("RightAns");
				this.OnRightAnsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Date NOT NULL")]
	public System.DateTime Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Result")]
public partial class Result : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Result_id;
	
	private string _Players;
	
	private string _Score;
	
	private System.DateTime _Date;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResult_idChanging(int value);
    partial void OnResult_idChanged();
    partial void OnPlayersChanging(string value);
    partial void OnPlayersChanged();
    partial void OnScoreChanging(string value);
    partial void OnScoreChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    #endregion
	
	public Result()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Result_id
	{
		get
		{
			return this._Result_id;
		}
		set
		{
			if ((this._Result_id != value))
			{
				this.OnResult_idChanging(value);
				this.SendPropertyChanging();
				this._Result_id = value;
				this.SendPropertyChanged("Result_id");
				this.OnResult_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Players", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string Players
	{
		get
		{
			return this._Players;
		}
		set
		{
			if ((this._Players != value))
			{
				this.OnPlayersChanging(value);
				this.SendPropertyChanging();
				this._Players = value;
				this.SendPropertyChanged("Players");
				this.OnPlayersChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Score
	{
		get
		{
			return this._Score;
		}
		set
		{
			if ((this._Score != value))
			{
				this.OnScoreChanging(value);
				this.SendPropertyChanging();
				this._Score = value;
				this.SendPropertyChanged("Score");
				this.OnScoreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
	public System.DateTime Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
