<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Start.aspx.cs" Inherits="Player_Start" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <%--<script type="text/html">
        function myrefresh(){
            window.location.reload();
        }
        setTimeout('myrefresh()',20000);
    </script>--%>

    <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <style type="text/css">
        
        header {
            height:60px;
            text-align: center;
            background-color: #188cb9;
            font: 15px kaiti;
            color: #e2ecf0;
            margin-bottom:0px auto;
        }
        #group {
           height:22px;
           background-color:#e2ecf0;
           margin:0px;
           text-align:right;
           
        }
        #content{
           border:5px outset  #e2ecf0;
           height:430px;
           margin:10px 50px 10px 50px;
          
        }
        #score {
           margin-top:10px;
           margin-left:40px;   
           width:550px; 
           height:460px;    
           float:left;
           border:5px solid #188cb9;
        }
        #title {
         margin-top:10px;
         margin-right:40px;
         width:550px; 
         height:460px;
         float:right ;
         border:5px solid #188cb9;
        
        }
        #lblTitle {
        width:400px;
        float:right;
        margin-top:40px;
        margin-right:90px;
        font-size:20px;
        }
        #cbk {
        width:400px;
        float:right;
        margin-top:20px;
        margin-right:100px;
        }
        #submit {
        float:right;
        margin-right:430px;
        
        }

        footer {
            clear:both;
            height:50px;
            text-align:center;
            background-color:#d2d2d2;

        }
      
        .auto-style1 {
            height: 67px;
        }
      
        .auto-style2 {
            height: 52px;
        }
       .send_message{
            display:none;
          
        }
      
    </style>

         <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="../Scripts/jquery-1.9.1.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        var timerStart = false;

    

        var t = 19;//设定跳转的时间 

        function refer() {
            document.getElementById('show').innerHTML = t; // 显示倒计时 
            t--; // 计数器递减 
        }

        function refre_time() {
            t = 19;
            if (!timerStart) {
                setInterval("refer()", 1000); //启动1秒定时 
                timerStart = true;
            }
        
        }

        function check(obj) {
            $(".select_item").attr("checked", false);
            $(obj).attr("checked", true);
            $("#TextBox2").val($(obj).val());
        }

        function AnsTemplate(ans) {
            var template = "";
            if (ans != '' && ans != null) {
                template += "  <div class=\"input-group\"><span class=\"input-group-addon\"><input class=\"select_item\" type=\"radio\" aria-label=\"...\" value=\""+ ans +"\" onclick=\"check(this)\" > </span>";
                template += " <lable  class=\"form-control\" aria-label=\"...\">" + ans + "</lable>";
                template += "</div>";
            }
            return template;
        }

        $(document).ready(function () {

            $("#submit").hide();

            $("#title-content").html("<h1 style=\"color:red\">各位选手注意! 答题将在 6 秒钟后进行</h1>")
            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;


            chat.client.UpdateTitle = function (message) {
           
                if (message == 1) {
                    var html = "<div style=\"text-align:center\">"
                     html += "<h1 style=\"color:red\">答题结束,窗体将会关闭</h1>";
                     html += "<a href=\"javascript:window.opener=null;window.open('','_self');window.close();\">关闭</a>";
                     html += "</div>";
                    $("#title").html(html)
                }
                else {
                var data = $.parseJSON(message);
                var result = "<div class=\"panel panel-default\">";
                result += "<div class=\"panel-heading\"><span id=\"my_titleid\">" + data["TestID"] + "</span>." + data["TestTitle"] + "</div>";
                result += "<div class=\"panel-body\">";
                result += AnsTemplate(data["TestAns1"]);
                result += AnsTemplate(data["TestAns2"]);
                result += AnsTemplate(data["TestAns3"]);
                result += AnsTemplate(data["TestAns4"]);
                result += "</div>";;
                $("#title-content").html(result);
                $('#score ul').append('<h3>' + data["TestID"] + '.' + data["TestTitle"] + "</h3>")
                $("#submit").show();
                refre_time();
                }
            }



            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message.
             //   var encodedName = $('<div />').text(name).html();
            //    var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#score ul').append('<li><strong>' + name
                    + '</strong>:&nbsp;&nbsp;' + message + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#submit').click(function () {
                    chat.server.send($('#TextBox1').val(), $("#my_titleid").text(), $('#TextBox2').val());
                    $("#submit").hide();
                });
            });
        });
    </script>

</head>
<body>
    <form id="form1" runat="server">
        <asp:TextBox class="send_message" ID="TextBox1" runat="server" Text="test"></asp:TextBox>
         <asp:TextBox class="send_message" ID="TextBox2" runat="server"  Text="test"></asp:TextBox>
    <header> 
           <h1>知识竞赛抢答计分网</h1>
        </header>
        <div id="group">
             欢迎<asp:Label ID="Label1" runat="server" Text="" ></asp:Label>&nbsp;&nbsp;
             <a href="../Login.aspx" >安全退出</a>
        </div>
        
            <div id="score" style="overflow: auto">
                <ul>

                </ul>
      
            </div>

             <div id="title">
                 <div id="title-content">
                     
                 </div>
                

                 <div>
                    该题还有<span id="show" style="color:red"></span>秒
                 </div>

                 <div  class="btn btn-danger" id="submit"  style="display:inline-block">
                     提交
                 </div>
            </div>

          
       
         <footer>
          <hr /> 版权所有
        </footer>
    </form>
</body>
</html>
